HelloMicroverse UI
lordksix/hello-microverse pull request #2
Opened 2023-03-21 15:35 UTC by lordksix

# Milestone 1: Project finished
In this milestone the project was finished:
- Added GitHub Actions to automate linter.
- Added HTML file with a **"Hello Microverse!"** heading
- Added a stylesheet for the HTML file
- Added .gitignore file to ignore node_modules, test.md, among other files.
- Added test.md file to test .gitignore file.

2023-03-21 16:22 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @lordksix   
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Good job setting up your first project at microverse 👍 , but   I think It would be better if you use all the section present in the  README found in this [template](https://github.com/microverseinc/readme-template), as It will make  your work to look more professional.  
- [ ] Also make sure you customize these sections with the data related to your project 👍 

- [x] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 16:22 UTC, iambenkis commented on README.md
> +<!-- PROJECT DESCRIPTION -->
- [ ] Good job setting up your first project at microverse 👍 , but   I think It would be better if you use all the section present in the  README found in this [template](https://github.com/microverseinc/readme-template), as It will make  your work to look more professional. 😃

2023-03-21 17:41 UTC, lordksix commented on README.md
> +<!-- PROJECT DESCRIPTION -->
@iambenkis Thank you :ok_hand:  . I made the changes requested and it definitely looks better. Thanks for the feedback.

2023-03-22 19:32 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @lordksix    👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
## Highlight 
✔ Used correct GitFlow👍 
✔ No Linter Errors 👍 

## Required Changes ♻️

- [ ]  Check the comments below 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 19:32 UTC, TuyishimireEric commented on README.md
> +
- [ ] **Good job so far 👏 👏**, Kindly as suggested by the previous reviewer, I think it would be better to customize this section with the data related to your project on how to get started, This one of the most important parts in a README as it helps the user to use your project, 🙏 

 ##### For Example:

### Prerequisites

In order to run this project you need:
To clone or fork and run it in a browser

<!--
Example command:

```sh
 gem install rails
```
 -->

### Setup

Clone this repository to your desired folder:




```sh
  cd my-folder
  git clone git@github.com:lordksix/hello-microverse.git
```
---
You may try to give the guides to the user to get started 🙏

2023-03-22 20:06 UTC, lordksix commented on README.md
> +
How to clone a repo is out of the scope of my project, but I added more specific information and GitHub documentation on how to clone or fork files

2023-03-22 20:12 UTC, braincee approved these changes
Hi @lordksix , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] [OPTIONAL] KIndly resolve all merge conflicts in your pull request

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-22 20:19 UTC, merged